CREATE TABLE IF NOT EXISTS ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    VALUE TEXT NOT NULL
);

DELETE FROM ITEMS;
INSERT INTO ITEMS (VALUE) VALUES ('Milk');
INSERT INTO ITEMS (VALUE) VALUES ('Coffee');
