CREATE TABLE IF NOT EXISTS ITEMS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    VALUE TEXT NOT NULL
)
GO

INSERT INTO ITEMS (VALUE) VALUES ('Milk')
GO
INSERT INTO ITEMS (VALUE) VALUES ('Coffee')
GO
